import React from "react";
import "../../styles/menuStyles/menuStyle.css";
import biryani from "../../assets/Biryani.avif";

export default function Biryani() {
  return (
    <div className="container">
      <div className="border">
        <h1 className="heading">Biryani Recipe</h1>
        <div className="image-container">
          <img src={biryani} alt="Biryani" className="img" />
        </div>
        <p className="first-heading">
          <h2 className="sub-heading">Ingredients:</h2>
          <ol className="list">
            <li>2 cups basmati rice</li>
            <li>500 grams chicken, cut into pieces</li>
            <li>1/2 cup yogurt</li>
            <li>2 onions, sliced</li>
            <li>3 tomatoes, chopped</li>
            <li>4 green chilies, slit</li>
            <li>2 tablespoons ginger-garlic paste</li>
            <li>1 teaspoon red chili powder</li>
            <li>1/2 teaspoon turmeric powder</li>
            <li>1/2 teaspoon garam masala powder</li>
            <li>1/4 cup mint leaves</li>
            <li>1/4 cup coriander leaves</li>
            <li>Salt to taste</li>
            <li>2 tablespoons ghee</li>
            <li>2 tablespoons oil</li>
            <li>2 cups water</li>
          </ol>
          <h2 className="sub-heading">Time to Cook:</h2>
          <ol className="list">
            <li>Preparation Time: 30 minutes</li>
            <li>Cooking Time: 45 minutes</li>
            <li>Total Time: Approximately 1 hour 15 minutes</li>
          </ol>
          <h2 className="sub-heading">Process:</h2>
          <ol className="list">
            <li>
              <b>Marinate Chicken:</b> In a bowl, mix yogurt, ginger-garlic
              paste, red chili powder, turmeric powder, and salt. Add chicken
              pieces, mint leaves, and coriander leaves. Marinate for at least
              30 minutes.
            </li>
            <li>
              <b>Prepare Rice:</b> Rinse basmati rice and soak in water for 30
              minutes. Drain the water.
            </li>
            <li>
              <b>Cook Rice:</b> In a large pot, bring water to boil. Add rice
              and cook until it is 70% done. Drain the water and keep aside.
            </li>
            <li>
              <b>Sauté Onions:</b> In a separate pan, heat ghee and oil. Fry
              sliced onions until golden brown. Remove and set aside.
            </li>
            <li>
              <b>Cook Chicken:</b> In the same pan, add marinated chicken and
              cook until it is half done. Add chopped tomatoes and cook until
              chicken is fully cooked and tomatoes are mushy.
            </li>
            <li>
              <b>Layer Biryani:</b> In a large heavy-bottomed pot, layer cooked
              rice and chicken masala alternatively. Sprinkle fried onions,
              garam masala powder, and slit green chilies between the layers.
            </li>
            <li>
              <b>Dum Cooking:</b> Cover the pot with a tight-fitting lid. Cook
              on low heat for 15-20 minutes until the flavors are well infused.
            </li>
            <li>
              <b>Serve:</b> Serve hot with raita or salad.
            </li>
          </ol>
        </p>
        <h5 className="end">generated by ChatGPT</h5>
      </div>
    </div>
  );
}
