import React from "react";
import "../../styles/menuStyles/menuStyle.css";
import cupcake from "../../assets/Cupcakes.avif";

export default function Cupcake() {
  return (
    <div className="container">
      <div className="border">
        <h1 className="heading">Cupcake Recipe</h1>
        <p className="first-heading">
          <h2 className="sub-heading">Ingredients:</h2>
          <ol className="list">
            <li>1 1/2 cups all-purpose flour</li>
            <li>1 1/2 teaspoons baking powder</li>
            <li>1/4 teaspoon salt</li>
            <li>1/2 cup unsalted butter, softened</li>
            <li>3/4 cup granulated sugar</li>
            <li>2 large eggs, at room temperature</li>
            <li>1 teaspoon vanilla extract</li>
            <li>1/2 cup milk</li>
          </ol>
          <h2 className="sub-heading">Time to Cook:</h2>
          <ol className="list">
            <li>Preparation Time: 10 minutes</li>
            <li>Baking Time: 18-20 minutes</li>
            <li>Total Time: Approximately 30 minutes</li>
          </ol>
          <h2 className="sub-heading">Process:</h2>
          <ol className="list">
            <li>
              <b>Preheat the Oven:</b> Preheat your oven to 350°F (175°C). Line
              a muffin tin with cupcake liners.
            </li>
            <li>
              <b>Combine Dry Ingredients:</b> In a medium bowl, whisk together
              the flour, baking powder, and salt. Set aside.
            </li>
            <li>
              <b>Cream Butter and Sugar:</b> In a large mixing bowl, cream
              together the softened butter and granulated sugar until light and
              fluffy.
            </li>
            <li>
              <b>Add Eggs and Vanilla:</b> Beat in the eggs one at a time, then
              stir in the vanilla extract.
            </li>
            <li>
              <b>Alternate Adding Ingredients:</b> Gradually add the dry
              ingredients to the wet mixture, alternating with the milk. Begin
              and end with the dry ingredients, mixing until just combined. Do
              not overmix.
            </li>
            <li>
              <b>Fill Cupcake Liners</b> Spoon the batter into the prepared
              cupcake liners, filling each about 2/3 full.
            </li>
            <li>
              <b>Bake:</b> Place the muffin tin in the preheated oven and bake
              for 18-20 minutes, or until a toothpick inserted into the center
              of a cupcake comes out clean.
            </li>
            <li>
              <b>Cool:</b> Remove the cupcakes from the oven and allow them to
              cool in the pan for a few minutes before transferring them to a
              wire rack to cool completely.
            </li>
            <li>
              <b>Decorate (Optional):</b> Once cooled, you can decorate your
              cupcakes with frosting, sprinkles, or any toppings of your choice.
            </li>
            <li>
              <b>Serve:</b> Serve and enjoy your delicious homemade cupcakes!
            </li>
          </ol>
        </p>
        <h5 className="end">generated by ChatGPT</h5>
      </div>
    </div>
  );
}
