import React from "react";
import "../../styles/menuStyles/menuStyle.css";
import mangoJuice from "../../assets/MangoJuice.jpg";

export default function MangoJuice() {
  return (
    <div className="container">
      <div className="border">
        <h1 className="heading">Mango Juice Recipe</h1>
        <div className="image-container">
          <img src={mangoJuice} alt="Mango Juice" className="img" />
        </div>
        <p className="first-heading">
          <h2 className="sub-heading">Ingredients:</h2>
          <ul className="list">
            <li>2 ripe mangoes, peeled and diced</li>
            <li>2 cups cold water</li>
            <li>2 tablespoons sugar (optional, adjust to taste)</li>
            <li>Ice cubes</li>
          </ul>
          <h2 className="sub-heading">Time to Prepare:</h2>
          <ul className="list">
            <li>Preparation Time: 10 minutes</li>
            <li>Total Time: Approximately 10 minutes</li>
          </ul>
          <h2 className="sub-heading">Instructions:</h2>
          <ol className="list">
            <li>
              <b>Prepare Mangoes:</b> Peel and dice the ripe mangoes.
            </li>
            <li>
              <b>Blend:</b> In a blender, add the diced mangoes, cold water, and
              sugar (if using). Blend until smooth.
            </li>
            <li>
              <b>Strain (Optional):</b> If desired, strain the mango puree
              through a fine mesh sieve to remove any fibrous bits.
            </li>
            <li>
              <b>Serve:</b> Pour the mango juice into glasses over ice cubes.
              Garnish with mango slices or mint leaves if desired. Serve
              immediately and enjoy!
            </li>
          </ol>
        </p>
        <h5 className="end">generated by ChatGPT</h5>
      </div>
    </div>
  );
}
