import React from "react";
import "../../styles/menuStyles/menuStyle.css";
import ramen from "../../assets/Noodles.avif";

export default function Ramen() {
  return (
    <div className="container">
      <div className="border">
        <h1 className="heading">Noodles</h1>
        <div className="image-container">
          <img src={ramen} alt="Ramen" className="img" />
        </div>
        <p className="first-heading">
          <h2 className="sub-heading">Ingredients:</h2>
          <ul className="list">
            <li>2 packs of ramen noodles</li>
            <li>4 cups chicken or vegetable broth</li>
            <li>2 cups water</li>
            <li>2 tablespoons soy sauce</li>
            <li>1 tablespoon miso paste (optional)</li>
            <li>1 tablespoon sesame oil</li>
            <li>2 cloves garlic, minced</li>
            <li>1 tablespoon ginger, grated</li>
            <li>1 cup sliced mushrooms</li>
            <li>1 cup shredded cooked chicken or tofu (optional)</li>
            <li>Sliced green onions, for garnish</li>
            <li>Sliced boiled egg, for garnish (optional)</li>
            <li>Nori seaweed, for garnish (optional)</li>
            <li>Chili oil or Sriracha, for spice (optional)</li>
          </ul>
          <h2 className="sub-heading">Time to Prepare:</h2>
          <ul className="list">
            <li>Preparation Time: 10 minutes</li>
            <li>Cooking Time: 15 minutes</li>
            <li>Total Time: Approximately 25 minutes</li>
          </ul>
          <h2 className="sub-heading">Instructions:</h2>
          <ol className="list">
            <li>
              <b>Prepare Broth:</b> In a large pot, combine the chicken or
              vegetable broth, water, soy sauce, miso paste (if using), sesame
              oil, minced garlic, and grated ginger. Bring to a simmer over
              medium heat.
            </li>
            <li>
              <b>Cook Noodles:</b> While the broth is simmering, cook the ramen
              noodles according to package instructions. Drain and set aside.
            </li>
            <li>
              <b>Add Mushrooms:</b> Once the broth is simmering, add the sliced
              mushrooms and shredded chicken or tofu (if using). Let simmer for
              a few minutes until the mushrooms are tender.
            </li>
            <li>
              <b>Assemble Ramen:</b> Divide the cooked noodles into serving
              bowls. Ladle the hot broth over the noodles, making sure to
              distribute the mushrooms and chicken/tofu evenly.
            </li>
            <li>
              <b>Garnish:</b> Garnish the ramen with sliced green onions, boiled
              egg, nori seaweed, and chili oil or Sriracha for spice, if
              desired.
            </li>
            <li>
              <b>Serve:</b> Serve the homemade ramen hot and enjoy!
            </li>
          </ol>
        </p>
        <h5 className="end">generated by ChatGPT</h5>
      </div>
    </div>
  );
}
