import React from "react";
import "../../styles/menuStyles/menuStyle.css";
import pancakes from "../../assets/Pancakes.avif";

export default function Pancakes() {
  return (
    <div className="container">
      <div className="border">
        <h1 className="heading">Homemade Pancake Recipe</h1>
        <div className="image-container">
          <img src={pancakes} alt="Pancakes" className="img" />
        </div>
        <p className="first-heading">
          <h2 className="sub-heading">Ingredients:</h2>
          <ul className="list">
            <li>1 cup all-purpose flour</li>
            <li>2 tablespoons granulated sugar</li>
            <li>1 teaspoon baking powder</li>
            <li>1/2 teaspoon baking soda</li>
            <li>1/4 teaspoon salt</li>
            <li>1 cup buttermilk</li>
            <li>1 large egg</li>
            <li>2 tablespoons unsalted butter, melted</li>
            <li>Butter or oil for cooking</li>
            <li>Maple syrup, fruit, or toppings of your choice</li>
          </ul>
          <h2 className="sub-heading">Time to Prepare:</h2>
          <ul className="list">
            <li>Preparation Time: 10 minutes</li>
            <li>Cooking Time: 10 minutes</li>
            <li>Total Time: Approximately 20 minutes</li>
          </ul>
          <h2 className="sub-heading">Instructions:</h2>
          <ol className="list">
            <li>
              <b>Prepare Batter:</b> In a large bowl, whisk together the flour,
              sugar, baking powder, baking soda, and salt.
            </li>
            <li>
              <b>Mix Wet Ingredients:</b> In another bowl, whisk together the
              buttermilk, egg, and melted butter.
            </li>
            <li>
              <b>Combine:</b> Pour the wet ingredients into the dry ingredients
              and stir until just combined. Do not overmix; lumps are okay.
            </li>
            <li>
              <b>Cook Pancakes:</b> Heat a non-stick skillet or griddle over
              medium heat. Lightly grease with butter or oil. Pour about 1/4 cup
              of batter onto the skillet for each pancake. Cook until bubbles
              form on the surface, then flip and cook until golden brown on the
              other side.
            </li>
            <li>
              <b>Serve:</b> Serve the pancakes hot with maple syrup, fruit, or
              toppings of your choice. Enjoy!
            </li>
          </ol>
        </p>
        <h5 className="end">generated by ChatGPT</h5>
      </div>
    </div>
  );
}
